const YOUTUBE_URL_MIN = 20;
const YOUTUBE_URL_MAX = 100;
const EXTRACT_TIME_MIN = 0;
const EXTRACT_TIME_MAX = 23;
const INTERNAL_SERVER_ERROR = '서버 내부 오류';
const VERIFICATION_ERROR = '입력이 잘못되었습니다.'
const SUCCESSFULLY_REGISTERED = '성공적으로 등록되었습니다.'
const FETCH_INFO_ERROR_MESSAGE = '계정 정보를 가져올 수 없습니다.';

module.exports = {
    YOUTUBE_URL_MIN,
    YOUTUBE_URL_MAX,
    EXTRACT_TIME_MIN,
    EXTRACT_TIME_MAX,
    INTERNAL_SERVER_ERROR,
    VERIFICATION_ERROR,
    SUCCESSFULLY_REGISTERED,
    FETCH_INFO_ERROR_MESSAGE
};
